import { ChevronDown, Copy, Pencil, Trash2 } from "lucide-react";
import { useEffect, useMemo, useState } from "react";
import { taskRepository } from "../data/taskRepository";
import type { MainCategory, PlanPeriod, Task } from "../types/task";
import { getWeekEndKey, todayKey } from "../utils/date";
import { MAIN_CATEGORY_META, SUB_CATEGORY_OPTIONS, WEEKDAY_LABELS, extraContentLabel, isCourseTask, subCategoryLabel, taskDisplayName } from "../utils/taskMeta";

interface Props { refreshKey: number; onRefresh: () => void; notify: (text: string) => void; onEdit: (task: Task) => void; onDelete: (task: Task) => void; onCopy: (task: Task) => void; }
const order: MainCategory[] = ["school", "extraHomework", "interestClass", "temporary"];

export function TaskManagementPage(props: Props) {
  const [tasks, setTasks] = useState<Task[]>([]);
  const [periods, setPeriods] = useState<PlanPeriod[]>([]);
  const [filter, setFilter] = useState<"all" | "current" | "regular" | "holiday">("current");
  const [selected, setSelected] = useState<Set<string>>(new Set());
  const [showDone, setShowDone] = useState(false);
  const [showAllDone, setShowAllDone] = useState(false);
  const reload = () => Promise.all([taskRepository.listAll(), taskRepository.listPlanPeriods()]).then(([items, stages]) => { setTasks(items); setPeriods(stages); setSelected(new Set()); });
  useEffect(() => { reload(); }, [props.refreshKey]);
  const holidays = periods.filter((period) => period.type === "holiday");
  const currentHoliday = holidays.find((period) => period.isActive && todayKey() >= period.startDate && todayKey() <= period.endDate);
  const filtered = useMemo(() => tasks.filter((task) => {
    const boundHoliday = !!task.planPeriodId && holidays.some((period) => period.id === task.planPeriodId);
    if (filter === "all") return true;
    if (filter === "regular") return !boundHoliday;
    if (filter === "holiday") return boundHoliday;
    return currentHoliday ? task.planPeriodId === currentHoliday.id : !boundHoliday;
  }), [tasks, periods, filter, currentHoliday?.id]);
  const pending = filtered.filter((task) => !["done", "cancelled"].includes(task.status));
  const completed = filtered.filter((task) => ["done", "cancelled"].includes(task.status));
  const completedCutoff = new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString();
  const recentCompleted = completed.filter((task) => (task.completedAt ?? task.updatedAt) >= completedCutoff);
  const visibleCompleted = showAllDone ? completed : recentCompleted;
  const earlierCompletedCount = completed.length - recentCompleted.length;
  const toggle = (id: string) => setSelected((current) => { const next = new Set(current); next.has(id) ? next.delete(id) : next.add(id); return next; });
  const selectIds = (ids: string[]) => setSelected((current) => { const next = new Set(current); const all = ids.every((id) => next.has(id)); ids.forEach((id) => all ? next.delete(id) : next.add(id)); return next; });
  const batchDelete = async () => {
    if (!selected.size || !confirm(`确定删除已选的 ${selected.size} 项任务吗？任务会保留在本地记录中。`)) return;
    const count = await taskRepository.batchRemove([...selected]);
    await reload(); props.onRefresh(); props.notify(`已删除 ${count} 项任务`);
  };
  return <main className="mx-auto w-full max-w-6xl px-4 pb-28 pt-6 sm:px-6">
    <div className="mb-5 grid grid-cols-[1fr_auto_1fr] items-end gap-3"><span /><div className="text-center"><p className="text-xs font-semibold tracking-widest text-sage-700">TASKS</p><h1 className="mt-1 text-2xl font-semibold">任务管理</h1></div>{selected.size > 0 ? <button onClick={batchDelete} className="inline-flex items-center gap-2 justify-self-end rounded-xl bg-rose-600 px-4 py-2.5 text-sm font-semibold text-white"><Trash2 className="h-4 w-4" />删除已选（{selected.size}）</button> : <span />}</div>
    <PlanPeriodManager periods={holidays} currentHoliday={currentHoliday} onChanged={() => { reload(); props.onRefresh(); }} notify={props.notify} />
    <div className="mb-4 mt-6 flex flex-wrap items-center gap-2">{(["all", "current", "regular", "holiday"] as const).map((value) => <button key={value} onClick={() => setFilter(value)} className={`rounded-full px-3 py-1.5 text-xs ${filter === value ? "bg-ink text-white" : "bg-white text-stone-500"}`}>{value === "current" ? `当前阶段（${currentHoliday ? "假期" : "平时"}）` : { all: "全部", regular: "平时", holiday: "假期" }[value]}</button>)}<span className="text-xs text-stone-400">今天：{currentHoliday?.name ?? "平时"}</span><button onClick={() => selectIds(filtered.map((task) => task.id))} className="ml-auto rounded-full border bg-white px-3 py-1.5 text-xs text-stone-500">{filtered.length && filtered.every((task) => selected.has(task.id)) ? "取消全选当前筛选" : "全选当前筛选"}</button></div>
    <div className="space-y-5">{order.map((category) => <TaskGroup key={category} category={category} tasks={pending.filter((task) => task.mainCategory === category)} periods={periods} selected={selected} onToggle={toggle} onSelectGroup={selectIds} {...props} />)}</div>
    {completed.length > 0 && <section className="mt-6 rounded-2xl border border-stone-100 bg-white p-3 opacity-75 shadow-card"><button onClick={() => setShowDone(!showDone)} className="flex w-full items-center justify-between px-1 py-2 text-sm font-semibold text-stone-500">已完成任务 · {visibleCompleted.length}{!showAllDone && earlierCompletedCount > 0 ? `（另有 ${earlierCompletedCount} 项更早记录）` : ""}<ChevronDown className={`h-4 w-4 transition ${showDone ? "rotate-180" : ""}`} /></button>{showDone && <div className="mt-2 space-y-4">{order.map((category) => <TaskGroup key={category} category={category} tasks={visibleCompleted.filter((task) => task.mainCategory === category)} periods={periods} selected={selected} onToggle={toggle} onSelectGroup={selectIds} {...props} />)}{earlierCompletedCount > 0 && <button onClick={() => setShowAllDone(!showAllDone)} className="mx-auto block rounded-xl border px-4 py-2 text-xs font-semibold text-stone-500">{showAllDone ? "只显示最近 30 天" : "显示更早已完成任务"}</button>}</div>}</section>}
  </main>;
}

function TaskGroup({ category, tasks, periods, selected, onToggle, onSelectGroup, ...props }: Props & { category: MainCategory; tasks: Task[]; periods: PlanPeriod[]; selected: Set<string>; onToggle: (id: string) => void; onSelectGroup: (ids: string[]) => void }) {
  if (!tasks.length) return null;
  const standardOptions = SUB_CATEGORY_OPTIONS[category];
  const subgroupOptions = category === "temporary" ? ["travel", "leisure", "examCompetition", "other"].map((value) => standardOptions.find((option) => option.value === value)!).filter(Boolean) : standardOptions;
  const knownValues = new Set(subgroupOptions.map((option) => option.value));
  const groups = [...subgroupOptions.map((option) => ({ ...option, tasks: tasks.filter((task) => task.subCategory === option.value) })), { value: "legacyOther", label: "其他", tasks: tasks.filter((task) => !knownValues.has(task.subCategory)) }].filter((group) => group.tasks.length);
  return <section className="overflow-hidden rounded-2xl border border-stone-100 bg-white shadow-card"><header className="flex items-center gap-2 border-b bg-stone-50/60 px-4 py-3"><span className={`h-2.5 w-2.5 rounded-full ${MAIN_CATEGORY_META[category].dot}`} /><h2 className="font-semibold">{MAIN_CATEGORY_META[category].label}</h2><span className="text-xs text-stone-400">{tasks.length}</span><button onClick={() => onSelectGroup(tasks.map((task) => task.id))} className="ml-auto text-xs text-sage-700">{tasks.every((task) => selected.has(task.id)) ? "取消本组" : "选择本组"}</button></header><div className="space-y-3 p-3">{groups.map((subgroup) => <section key={subgroup.value} className="overflow-hidden rounded-xl border border-stone-100"><h3 className="bg-stone-50 px-3 py-2 text-xs font-semibold text-stone-600">{subgroup.label} · {subgroup.tasks.length}</h3>{subgroup.tasks.map((task) => <TaskRow key={task.id} task={task} periods={periods} selected={selected.has(task.id)} onToggle={() => onToggle(task.id)} {...props} />)}</section>)}</div></section>;
}

function TaskRow({ task, periods, selected, onToggle, onCopy, onEdit, onDelete }: Props & { task: Task; periods: PlanPeriod[]; selected: boolean; onToggle: () => void }) {
  const period = periods.find((item) => item.id === task.planPeriodId);
  const finished = ["done", "cancelled"].includes(task.status);
  return <div className={`flex items-center gap-2 border-b px-4 py-3 last:border-0 ${finished ? "bg-stone-50/40 text-stone-400" : ""}`}><input type="checkbox" checked={selected} onChange={onToggle} aria-label={`选择 ${task.title}`} className="h-4 w-4 rounded" /><div className="min-w-0 flex-1"><p className={`truncate text-sm font-medium ${finished ? "line-through" : ""}`}>{taskDisplayName(task)}</p><div className={`mt-1 flex flex-wrap items-center gap-1.5 text-[11px] ${finished ? "text-stone-400" : "text-stone-500"}`}><span className={`rounded px-1.5 py-0.5 ${finished ? "bg-stone-100 text-stone-400" : subjectTagClass(task)}`}>{subCategoryLabel(task.mainCategory, task.subCategory)}</span>{task.mainCategory === "extraHomework" && <span className={`rounded px-1.5 py-0.5 ${finished ? "bg-stone-200 text-stone-400" : contentTagClass(task)}`}>{extraContentLabel(task.extraContentType)}</span>}{task.mainCategory === "interestClass" && isCourseTask(task) && <span className={`rounded px-1.5 py-0.5 font-semibold ${finished ? "bg-stone-200 text-stone-400" : "bg-ink text-white"}`}>上课</span>}{task.applicablePeriodType === "regular" && <span className="rounded bg-stone-100 px-1.5 py-0.5">平时</span>}{period && <span className="rounded bg-sage-50 px-1.5 py-0.5 text-sage-700">假期·{period.name}</span>}<span>{timeLabel(task)}</span>{formatTime(task) && <span>｜{formatTime(task)}</span>}{task.calendarVisibility === "hide" && <span>｜不显示月历</span>}{task.rolloverMode === "skipIfMissed" && <span>｜过期自动跳过</span>}</div>{task.checklistItems?.length ? <p className="mt-1 text-[11px] text-stone-400">小项 {task.checklistItems.filter((item) => item.done).length}/{task.checklistItems.length}</p> : null}</div><button onClick={() => onCopy(task)} aria-label="复制" className="rounded-lg p-2 text-stone-500 hover:bg-stone-50"><Copy className="h-4 w-4" /></button><button onClick={() => onEdit(task)} aria-label="编辑" className="rounded-lg p-2 text-stone-500 hover:bg-stone-50"><Pencil className="h-4 w-4" /></button><button onClick={() => onDelete(task)} aria-label="删除" className="rounded-lg p-2 text-rose-500 hover:bg-rose-50"><Trash2 className="h-4 w-4" /></button></div>;
}

function PlanPeriodManager({ periods, currentHoliday, onChanged, notify }: { periods: PlanPeriod[]; currentHoliday?: PlanPeriod; onChanged: () => void; notify: (text: string) => void }) {
  const [open, setOpen] = useState(false);
  const [draft, setDraft] = useState({ name: "", startDate: todayKey(), endDate: todayKey() });
  const add = async () => { if (!draft.name.trim() || draft.startDate > draft.endDate) return notify("请填写正确的假期名称和日期"); await taskRepository.createPlanPeriod({ ...draft, type: "holiday", name: draft.name.trim(), isActive: true }); setDraft({ ...draft, name: "" }); onChanged(); notify("假期已添加"); };
  return <section className="rounded-2xl border border-stone-100 bg-white p-4 shadow-sm"><div className="flex items-center justify-between"><div><h2 className="font-semibold">假期设置</h2><p className="mt-1 text-xs text-stone-400">当前：{currentHoliday?.name ?? "平时"}；只需维护假期，其他日期自动视为平时</p></div><button onClick={() => setOpen(!open)} className="rounded-lg bg-sage-50 px-3 py-1.5 text-xs font-medium text-sage-700">{open ? "收起" : "管理假期"}</button></div>{open && <div className="mt-4"><div className="grid gap-2 sm:grid-cols-4"><input value={draft.name} onChange={(e) => setDraft({ ...draft, name: e.target.value })} placeholder="例如：2026暑假" className="rounded-lg border px-3 py-2 text-sm" /><input type="date" value={draft.startDate} onChange={(e) => setDraft({ ...draft, startDate: e.target.value })} className="rounded-lg border px-2 py-2 text-sm" /><input type="date" value={draft.endDate} onChange={(e) => setDraft({ ...draft, endDate: e.target.value })} className="rounded-lg border px-2 py-2 text-sm" /><button onClick={add} className="rounded-lg bg-ink px-3 py-2 text-sm font-semibold text-white">添加假期</button></div><div className="mt-3 space-y-2">{periods.map((period) => <div key={period.id} className="flex items-center gap-3 rounded-lg bg-stone-50 px-3 py-2 text-xs"><span className="font-medium">{period.name}</span><span className="text-stone-400">{period.startDate} 至 {period.endDate}</span><button onClick={async () => { await taskRepository.updatePlanPeriod(period.id, { isActive: !period.isActive }); onChanged(); }} className={`ml-auto rounded-full px-2 py-0.5 ${period.isActive ? "bg-emerald-50 text-emerald-700" : "bg-stone-200 text-stone-500"}`}>{period.isActive ? "启用" : "停用"}</button><button onClick={async () => { const name = prompt("假期名称", period.name)?.trim(); if (!name) return; const startDate = prompt("开始日期 YYYY-MM-DD", period.startDate); const endDate = prompt("结束日期 YYYY-MM-DD", period.endDate); if (!startDate || !endDate || startDate > endDate) return notify("日期范围不正确"); await taskRepository.updatePlanPeriod(period.id, { name, startDate, endDate }); onChanged(); }} className="text-sage-700">修改</button><button onClick={async () => { if (!confirm(`删除假期“${period.name}”？关联任务会改为全部阶段。`)) return; await taskRepository.removePlanPeriod(period.id); onChanged(); }} className="text-rose-500">删除</button></div>)}</div></div>}</section>;
}

function timeLabel(task: Task) { if (task.timeType === "weekGoal") return `${task.weeklyQuota?.isWeeklyRecurring ? "每周执行｜" : ""}本周目标${task.weekStart ? `｜${task.weekStart} 至 ${getWeekEndKey(task.weekStart)}` : ""}`; if (task.timeType === "assignmentWindow") return `作业周期：${task.assignmentWindow?.startDate ?? "?"}-${task.assignmentWindow?.endDate ?? "?"}`; if (task.schedulePattern === "specificDates") return `指定日期 ${task.specificDates?.join("、") ?? ""}`; if (task.schedulePattern === "dailyRecurring") return `每日重复｜${task.recurrence?.startDate ?? "?"} 至 ${task.recurrence?.endDate ?? "长期"}`; if (task.schedulePattern === "dateRangeDaily") return `${task.startDate}-${task.endDate} 每天`; if (task.schedulePattern === "dateRangeWeekdays") return `${task.startDate}-${task.endDate}｜每周${weekdayText(task.rangeWeekdays)}`; if (task.schedulePattern === "weeklyRecurring" || task.timeType === "recurring") return `每周${weekdayText(task.recurrence?.weekdays)}｜${task.recurrence?.startDate ?? "?"} 至 ${task.recurrence?.endDate ?? "长期"}`; if (task.timeType === "dateRange") return `${task.startDate ?? "?"}-${task.endDate ?? "?"}`; return task.date ?? "未设置日期"; }
const weekdayText = (days?: number[]) => [1, 2, 3, 4, 5, 6, 0].filter((day) => days?.includes(day)).map((day) => WEEKDAY_LABELS[day].replace("周", "")).join("");
const formatTime = (task: Task) => { const start = task.startTime ?? task.time; return start ? `${start}${task.endTime ? `-${task.endTime}` : ""}${task.estimatedMinutes ? `｜预计${task.estimatedMinutes}分钟` : ""}` : ""; };
function subjectTagClass(task: Task) { if (task.mainCategory === "readingPlan") return "bg-cyan-50 text-cyan-700"; if (task.mainCategory === "interestClass") return task.subCategory === "swimming" ? "bg-teal-50 text-teal-700" : task.subCategory === "rollerSkating" ? "bg-indigo-50 text-indigo-700" : "bg-fuchsia-50 text-fuchsia-700"; if (task.mainCategory === "temporary") return task.subCategory === "examCompetition" ? "bg-red-50 text-red-700" : task.subCategory === "travel" ? "bg-rose-50 text-rose-700" : "bg-stone-100 text-stone-600"; return task.subCategory === "chinese" ? "bg-pink-50 text-pink-700" : task.subCategory === "math" ? "bg-blue-50 text-blue-700" : task.subCategory === "english" ? "bg-emerald-50 text-emerald-700" : "bg-stone-100 text-stone-600"; }
function contentTagClass(task: Task) { return task.extraContentType === "class" ? "bg-ink text-white" : task.extraContentType === "homework" ? "bg-orange-50 text-orange-700" : task.extraContentType === "practice" ? "bg-indigo-50 text-indigo-700" : task.extraContentType === "dictation" ? "bg-violet-50 text-violet-700" : task.extraContentType === "recitation" ? "bg-amber-50 text-amber-800" : "bg-stone-100 text-stone-600"; }
