import { addDays } from "date-fns";
import { CalendarClock, ChevronLeft, ChevronRight, WandSparkles } from "lucide-react";
import { useEffect, useState } from "react";
import { TaskItem } from "../components/TaskItem";
import { taskRepository } from "../data/taskRepository";
import type { PlanOverviewItem, Task, TaskDisplay, TaskStatus } from "../types/task";
import { formatCompactDate, fromDateKey, getWeekEndKey, getWeekStartKey, toDateKey, todayKey } from "../utils/date";
import { TASK_SUBJECT_GROUPS, taskSubjectGroup } from "../utils/taskGrouping";
import { taskDisplayName } from "../utils/taskMeta";

interface Props { date: string; refreshKey: number; onDateChange: (date: string) => void; onRefresh: () => void; onEdit: (task: TaskDisplay) => void; onDelete: (task: TaskDisplay) => void; onCopy: (task: TaskDisplay) => void; onStatusChange: (task: TaskDisplay, status: TaskStatus) => void; onOccurrenceCancel: (task: TaskDisplay) => void; onOccurrencePostpone: (task: TaskDisplay) => void; onChecklistToggle: (task: TaskDisplay, itemId: string) => void; notify: (text: string) => void; }

export function WeekPage(props: Props) {
  const start = getWeekStartKey(props.date);
  const dates = Array.from({ length: 7 }, (_, index) => toDateKey(addDays(fromDateKey(start), index)));
  const [pools, setPools] = useState<(Task & { arranged: number })[]>([]);
  const [days, setDays] = useState<Record<string, TaskDisplay[]>>({});
  const [summary, setSummary] = useState<PlanOverviewItem[]>([]);
  useEffect(() => { Promise.all([taskRepository.getWeekPools(start), taskRepository.getWeekOverview(start), ...dates.map((date) => taskRepository.getTasksForDate(date))]).then(async ([poolTasks, overview, ...daily]) => { const withCounts = await Promise.all((poolTasks as Task[]).map(async (task) => { const children = await taskRepository.getChildren(task.id, start); const arranged = task.weeklyQuota ? Math.min(task.weeklyQuota.targetCount, children.reduce((sum, child) => sum + (child.amountPerSession ?? 1), 0)) : children.length; return { ...task, arranged }; })); setPools(withCounts); setSummary(overview as PlanOverviewItem[]); setDays(Object.fromEntries(dates.map((date, index) => [date, daily[index] as TaskDisplay[]]))); }); }, [start, props.refreshKey]);
  const allocate = async (id: string) => { try { const count = await taskRepository.allocateTask(id, start); props.notify(`已安排 ${count} 个执行项`); props.onRefresh(); } catch (reason) { props.notify(reason instanceof Error ? reason.message : "分配失败"); } };
  const move = (days: number) => props.onDateChange(toDateKey(addDays(fromDateKey(start), days)));
  const rowProps = { compact: true, onStatusChange: props.onStatusChange, onEdit: props.onEdit, onDelete: props.onDelete, onCopy: props.onCopy, onOccurrenceCancel: props.onOccurrenceCancel, onOccurrencePostpone: props.onOccurrencePostpone, onChecklistToggle: props.onChecklistToggle };
  return <main className="mx-auto w-full max-w-7xl px-4 pb-28 pt-6 sm:px-6">
    <div className="mb-6 grid grid-cols-[1fr_auto_1fr] items-center gap-3"><button onClick={() => move(-7)} className="justify-self-start rounded-xl border bg-white px-3 py-2 text-sm"><span className="inline-flex items-center gap-1"><ChevronLeft className="h-5 w-5" />上一周</span></button><div className="text-center"><p className="text-xs font-semibold tracking-widest text-sage-700">WEEK PLAN</p><h1 className="mt-1 text-3xl font-semibold text-ink sm:text-4xl">本周计划 <span className="whitespace-nowrap text-base font-medium text-stone-500 sm:text-lg">（{formatCompactDate(start)} — {formatCompactDate(getWeekEndKey(start))}）</span></h1><button onClick={() => props.onDateChange(todayKey())} className="mt-3 rounded-xl bg-sage-50 px-5 py-2 text-sm font-semibold text-sage-700 hover:bg-sage-100">回到本周</button></div><button onClick={() => move(7)} className="justify-self-end rounded-xl border bg-white px-3 py-2 text-sm"><span className="inline-flex items-center gap-1">下一周<ChevronRight className="h-5 w-5" /></span></button></div>
    <section className="mb-4 rounded-2xl border border-stone-100 bg-white p-4 shadow-card"><h2 className="font-semibold">本周汇总</h2><div className="mt-3 grid grid-cols-1 gap-3 sm:grid-cols-2 xl:grid-cols-4">{TASK_SUBJECT_GROUPS.map((subject) => { const group = summary.filter((item) => item.group === subject.key); return <section key={subject.key} className="rounded-xl bg-stone-50 p-3"><h3 className="text-sm font-semibold text-stone-700">{subject.label}</h3><div className="mt-2 space-y-2">{group.length ? group.map((item) => { const unfinished = item.done < item.total; return <div key={item.id} className={`flex items-center justify-between gap-2 rounded-md border-l-2 px-2 py-1.5 text-xs ${unfinished ? "border-amber-400 bg-amber-50 font-medium text-stone-700" : "border-stone-200 text-stone-400"}`}><span className="min-w-0 truncate">{item.label}</span>{item.isCourse && <span className={`shrink-0 rounded px-1.5 py-0.5 text-[9px] font-semibold ${unfinished ? "bg-ink text-white" : "bg-stone-200 text-stone-400"}`}>上课</span>}<span className="shrink-0 tabular-nums">{item.done} / {item.total} {item.unit}</span></div>; }) : <p className="text-xs text-stone-300">暂无</p>}</div></section>; })}</div></section>
    {pools.length > 0 && <section className="mb-6 rounded-2xl border border-stone-100 bg-white p-4 shadow-card"><div className="mb-3 flex items-center gap-2"><CalendarClock className="h-5 w-5 text-sage-700" /><h2 className="font-semibold">每周目标与进行中的作业</h2></div><div className="space-y-2">{pools.map((task) => <div key={task.id} className="flex flex-col gap-2 rounded-xl bg-stone-50 px-4 py-3 sm:flex-row sm:items-center sm:justify-between"><div><p className="text-sm font-medium text-ink">{taskDisplayName(task)}</p><p className="mt-1 text-xs text-stone-500">已安排 {task.arranged}/{task.weeklyQuota?.targetCount ?? task.splitCount ?? task.totalAmount ?? 1}{task.weeklyQuota?.isWeeklyRecurring && " · 每周执行"}{task.assignmentWindow && ` · 周期 ${task.assignmentWindow.startDate} 至 ${task.assignmentWindow.endDate}`}</p></div><div className="flex gap-2"><button onClick={() => props.onEdit(task)} className="rounded-lg px-3 py-1.5 text-xs text-stone-600 hover:bg-white">编辑</button>{task.weeklyQuota?.allowAutoDistribute !== false && <button onClick={() => allocate(task.id)} className="inline-flex items-center gap-1 rounded-lg bg-ink px-3 py-1.5 text-xs font-semibold text-white"><WandSparkles className="h-3.5 w-3.5" />一键分配</button>}</div></div>)}</div></section>}
    <section><h2 className="mb-3 font-semibold text-ink">每日安排</h2><div className="grid gap-3 lg:grid-cols-2 xl:grid-cols-3">{dates.map((date) => { const dayTasks = days[date] ?? []; return <div key={date} className="overflow-visible rounded-2xl border border-stone-100 bg-white"><button onClick={() => props.onDateChange(date)} className="flex w-full items-center justify-between border-b px-4 py-3 text-left"><span className="font-semibold">{["一", "二", "三", "四", "五", "六", "日"][dates.indexOf(date)]} <span className="ml-1 text-xs font-normal text-stone-400">{formatCompactDate(date)}</span></span><span className="text-xs text-stone-400">{dayTasks.length} 项</span></button>{dayTasks.length ? <div className="space-y-3 p-3">{TASK_SUBJECT_GROUPS.map((subject) => { const group = dayTasks.filter((task) => taskSubjectGroup(task) === subject.key); if (!group.length) return null; return <section key={subject.key} className="overflow-visible rounded-xl border border-stone-100"><h3 className="border-b bg-stone-50 px-3 py-1.5 text-xs font-semibold text-stone-600">{subject.label}</h3>{group.map((task) => <TaskItem key={`${task.id}:${task.occurrenceDate ?? task.date}`} task={task} {...rowProps} />)}</section>; })}</div> : <p className="px-4 py-5 text-sm text-stone-400">暂无安排</p>}</div>; })}</div></section>
  </main>;
}
